# GitHub displays this link through the repository's Sponsor button. Funding is
# voluntary and does not change the software license or issue priority.
custom:
  - https://buymeacoffee.com/master_chief
